# Generated by Django 3.1.1 on 2020-12-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='person',
            name='l_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
