# Generated by Django 3.1.1 on 2021-03-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_contact_donor_support_supportus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Support',
            new_name='Vol',
        ),
    ]
